### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by Draky50110** [Alkarex/EasyRSS#12]
Hello.

Can't connect :/

Which URL do I need to have ?
My FRSS is http://domain.com/frss/ do I input this directly on login screen ?
@Alkarex I open this issue here instead of the FRSS project, because I don't know if the problem is about the app or my FRSS install...

**Comment by Draky50110** [comment]
Found the problem : you must enter the full path to greader.php !
Maybe should be automatically "discovered" ?

**Comment by Alkarex** [comment]
Yes indeed, the full path is needed. I will consider adding a special case for FreshRSS.

**Comment by Draky50110** [comment]
I will make some suggestions in another issue ;) after some days of use :)
