### ISSUE TITLE
Tcp Port

### ISSUE THREAD

**Issue by ebal** [Alkarex/EasyRSS#14]
I am running a FreshRSS instance over SSL, on a different tcp port than 443.

eg. https://FreshRSS.mydomain.tld:8888

Testing easyrss app to my server with tcpdump opened, seems that no traffic is reaching to my server. Remove the port part from the url and traffic is reaching the server just fine.

Reading through the code, I am not sure that there is a port definition but only if the connection is http or https. 

Can you PLZ provide such functionality ?
Thanks in advance

**Comment by Alkarex** [comment]
I will try to find time to add support for that.

**Comment by Alkarex** [comment]
I have just had a quick look at it, and it seems that the port is correctly parsed from the URL when using a string such as `https://example.net:8888/p/api/greader.php`

![port](https://cloud.githubusercontent.com/assets/1008324/14404040/953d45bc-fe6d-11e5-9cb8-0dfc496bec3a.png)

**Comment by ebal** [comment]
Hi there, 
thanks for looking up on this issue.

Unfortunately it seems that I can not Login/Connect with easyRSS to my FreshRSS setup.

Using: https://FreshRSS.example.com:8888/p/api/greader.php
with username // password 

the EasyRSS android app does not do anything and reports a Login Failed msg.
I dont even see any log entries on my apache logs.

exactly the same URL on the android browser and I am getting hits on apache's logs.
I can confirm that I can login from the android browser.

I thought it was the port setup but perhaps it is something else.
I use a self singed certificate for this. Perhaps that's the issue, although I have already added via security options on my android device.

If you have the time, I would appropriate your input.
-ebal

**Comment by Alkarex** [comment]
Could you give a try in plain HTTP ? It is probably the certificate indeed.

**Comment by ebal** [comment]
Just tested without SSL (that means without any port either)
http://example.com/FreshRSS/p/api/greader.php
username // password
, same result.

Tested with a Lets Encrypt SSL, same result.

Login Failed from EasyRSS, everything is ok with the android browser (every time).



with http (and no port) I get an 401 Unauthorized msg

"POST /FreshRSS/p/api/greader.php/accounts/ClientLogin HTTP/1.1" 401 33 "-" "Dalvik/1.6.0 (Linux; U; Android 4.2.2;

I will try to spent, tomorrow, some more time investigation this but I would prefer to use https (and a custom port) for security.

thanks

**Comment by ebal** [comment]
@Alkarex 

I am really -really- sorry for this git issue, in the end the problem was related to this:
https://github.com/FreshRSS/FreshRSS/issues/962

and not to EasyRSS.

**Comment by Alkarex** [comment]
Ok, nevermind, and thanks for the feedback.
