### ISSUE TITLE
No more items with large list of feeds

### ISSUE THREAD

**Issue by Asara** [Alkarex/EasyRSS#16]
Hey,

Currently using FreshRSS as the backend.  Every time EasyRSS pulls more than ~500 items, my 'Unread' queue shows 'No more items' but all the articles are in my 'All' queue.

The only fix I have come across is reading them on the server, marking them as read and then resetting EasyRSS, which is tedious.  

Any idea why this could be occurring?  

Thanks!

**Comment by Alkarex** [comment]
Hum, I have just tested with > 900 without problem. Could you try to increase the number of articles to store in the EasyRSS settings?

**Comment by Asara** [comment]
It was set to 2000 (default). Upped it to 4000.  Will update if I run into the same issue again

**Comment by Asara** [comment]
Currently have 426 unread items, All shows 426 items as well, but when I go to All items under All, it shows articles from >5 days ago. 

On the flip side, when going to All unread items under Unread, I once again get No more items.

**Comment by Asara** [comment]
It seems as if this only happens when I set Descending items sorting to off.

**Comment by Asara** [comment]
Still having this issue and haven't found a good way to fix it.  Is there any way to get EasyRSS to only pull 'New' items and ignore the read ones?

**Comment by Asara** [comment]
@Alkarex 
Just pinging again to find out if there is any way to only pull 'New' items from FreshRSS

Thanks!

**Comment by planetahuevo** [comment]
Hi @Alkarex 
It happens to me too but I have the descending items ON.
I cannot find a pattern but some categories or blogs does not show the number but it shows the "Load more Items" button, but this only work when there is a connection so I cannot read them.

I have 4000 on the number of articles and a total of 2000 stored, so the space is not a problem.

Could this fork and commit fix this?
https://github.com/scastrorico/EasyRSS/commit/a44151603e5e24e1dddd36ff74ee12e0339553b1

**Comment by Alkarex** [comment]
@Asara @planetahuevo Sorry for the delay, I am mainly working on FreshRSS with not so much time left for EasyRSS :-( I would be welcoming some contributors, by the way.
@planetahuevo I do not think this patch would make a difference.
@Asara I believe it would require to revise a bit the synchronisation logic of EasyRSS, in which a number of things are not currently done optimally.

**Comment by Asara** [comment]
@Alkarex no stress on the delay.  At this point I have no mobile solution for RSS since EasyRSS does't work (pretty much at all at this point for me) with FreshRSS.

Could you give me a hint as to where to look? Can't say I know much android/java but I can mess around with it.

Thanks for all the work @Alkarex

**Comment by planetahuevo** [comment]
@Alkarex No problem. :+1: 
Not a big issue if you have internet connection. 
I am not a developer myself so I cannot help much with code, but with tests and comments. :(

**Comment by hrehfeld** [comment]
I think I run into the same issue, also  with "descending articles" off. If I turn it on, I get some updates.

**Comment by Asara** [comment]
This doesn't seem to be an issue anymore. I have switched clients so that might be why. Closing this issue. 

Thanks for the awesome work @Alkarex
