### ISSUE TITLE
Less time between refreshes

### ISSUE THREAD

**Issue by Draky50110** [Alkarex/EasyRSS#19]
Hello.

Is it possible to have less than one hour for refresh time ?
More choices or directly an input textarea.

FreshRSS does not allow less than 20 minutes but would be nice to choose even 20 minutes in the app :)

**Comment by Alkarex** [comment]
Done https://github.com/Alkarex/EasyRSS/commit/30ab6547dd37670e9b97d174c48c79e5c65d9944
But please note that I have not checked the auto-synchronisation recently, and I am not sure it is working properly
