### ISSUE TITLE
Update API URL

### ISSUE THREAD

**Issue by Iron-Wolf** [Alkarex/EasyRSS#22]
Hello

Thank you for developing such a great RSS reader :+1: 

By the way, I just discovered EasyRSS, but I had trouble to get the correct URL to put in the application.
Actually, I saw a lot of url like this : 
- http://my_server/**p/api/greader.php**
- http://my_server/**FreshRSS/p/api/greader.php**

But I finally managed to get the right URL with this one :
- http://my_server/**api/greader.php**

So I just post here to let you know that some informations like this one are not up to date. I just want to contribute for future users (maybe they will try wrong URLs like me).

(In fact, I don't know if the documentation or your README is wrong, or if the application behave normally.)

**Comment by monsieurpouet** [comment]
I think that depends of your virtual host.
Your virtual host link into your freshrss directory is like /var/www/freshrss.

In your Apache2 VH you've DocumentRoot /var/www/freshrss. So your URL will be http://foo/api/greader.php
It's relative. I don't know you understand me. The README is relative to a standard installation.

**Comment by Iron-Wolf** [comment]
Off course the configuration is relative to your VH.
With that in mind, your README mention : https://your.server.example/FreshRSS/p/api/greader.php

In my case, the "p" was useless.
I should have mentioned it earlier.

**Comment by Alkarex** [comment]
I have just merged a patch in the /dev branch of FreshRSS, with a bit more help to find out which link to use for the API, on the same page where one defines the password for the API
https://github.com/FreshRSS/FreshRSS/pull/1186
Comments welcome
