### ISSUE TITLE
Unable to connect on Android 7.1

### ISSUE THREAD

**Issue by carlierromain** [Alkarex/EasyRSS#26]
Hi! 
I've recently updated my OnePlus One to Android 7.1 Nougat, and since the update I'm unable to connect EasyRSS to my server. 
No problem at all on my nvidia shield tablet (running android 6.0). Any idea? 
I'm addicted to easyRSS :)
Thanks!

**Comment by Alkarex** [comment]
Hello,
It is probably that you are typing the wrong address, or the wrong
credentials.
Please remember that the API password of FreshRSS is not necessarily the
same as the Web password.
You can also have a look at your Web server logs, as well as FreshRSS logs,
in particular ./data/users/_/log_api.txt

**Comment by carlierromain** [comment]
Hi,

I use the exact same address/user/password on my other android device and
everything is working.
To be sure I disconnected my account on my tablet, and copy/paste the same
address and credentials on my smartphone (7.1) and it keep saying
"connection failed please verify user and password".
I double check for the API password, even changed it for a new one.

Thanks for your quick response!

Le 17 nov. 2016 6:42 AM, "Alexandre Alapetite" <notifications@github.com> a
écrit :
>
> Hello,
> It is probably that you are typing the wrong address, or the wrong
> credentials.
> Please remember that the API password of FreshRSS is not necessarily the
> same as the Web password.
> You can also have a look at your Web server logs, as well as FreshRSS
logs,

**Comment by Alkarex** [comment]
Hello,
I do not have an Android 7 to try. But did you have a chance to look at the logs, in particular in particular `./data/users/_/log_api.txt` ?

**Comment by markybob** [comment]
just fyi, works here on 7 and 7.1.1 DP2.

**Comment by carlierromain** [comment]
Hi, I can't really explain how but after a software update of the installed ROM on my OnePlus One (Unofficial CM14.1 build : Tugapower N10) everything works just fine now.
With the previous versions of that ROM (N4 to N9) all my connection attempts to EasyRSS gave me the same kind of error message "wrong login".
