### ISSUE TITLE
Publish on Google Play

### ISSUE THREAD

**Issue by nikaro** [Alkarex/EasyRSS#27]
It would be nice to have it on Google Play store :-) I have a smartphone with GApps and i do not really want to install F-Droid and allow "untrusted" sources for apps…

**Comment by Alkarex** [comment]
It seems also to have disappeared from F-Droid https://f-droid.org/repository/browse/?fdid=org.freshrss.easyrss
I am not sure why

**Comment by Frenzie** [comment]
I downvoted that but obviously I mean I don't like the fact that I just searched for EasyRSS on F-Droid and couldn't find it.

The [F-Droid wiki](https://f-droid.org/wiki/page/org.freshrss.easyrss) says EasyRSS has:

>This app has the DisabledAlgorithm Antifeature.
>This app has the KnownVuln Antifeature.

I have no idea what DisabledAlgorithm is supposed to be, but KnownVuln sounds like it could be relevant? But if there's a known vulnerability why wouldn't anyone report it here? Questions, questions…

**Comment by Alkarex** [comment]
Thanks for the info, Franz.
The wiki history does not seem to contain a date for the change, so it
could be something automatic.
I have not received any warning prior to deletion.
It would be necessary to find time to build a new version in any case

Le 17 juil. 2017 21:18, "Frans de Jonge" <notifications@github.com> a
écrit :

**Comment by mimi89999** [comment]
@Alkarex At the time of the build of the latest version of EasyRSS F-Droid signed apps with an algorithm that is now considered as weak. Because of that, older builds signed with that algorithm were moved to the archive repo.

Best way of getting the app rebuilt would be bumping the version.

**Comment by Frenzie** [comment]
See https://gitlab.com/fdroid/fdroiddata/issues/788#note_35541404

**Comment by Alkarex** [comment]
Thanks for the info @mimi89999 and @Frenzie 👍

**Comment by Alkarex** [comment]
@mimi89999 @Frenzie I have made a special issue for the re-submission in F-Droid https://github.com/Alkarex/EasyRSS/issues/32
