### ISSUE TITLE
favorites are not updated from the server

### ISSUE THREAD

**Issue by oupala** [Alkarex/EasyRSS#28]
If some articles are un-favorited on the server (ie. with freshrss), the articles still appear as favorited in Easy RSS.

The favorites list should be updated from the server data.

I think Easy RSS assume that the reader will always use Easy RSS, and so the *un-favorite article* will happens on Easy RSS.

But if you also use another client (such as Fresh RSS), the *un-favorite* action might happens on Fresh RSS. In this case, Easy RSS should update himself depending on the from the server, **including favorite articles list**.

**Comment by oupala** [comment]
I think Easy RSS assume that the reader will always use Easy RSS, and so the *un-favorite article* will happens on Easy RSS.

But if you also use another client (such as Fresh RSS), the *un-favorite* action might happens on Fresh RSS. In this case, Easy RSS should update himself depending on the from the server, **including favorite articles list**.

**Comment by Gwend4l** [comment]
I observe the same problem

**Comment by Pazns** [comment]
This issue is still running.

**Comment by Pazns** [comment]
Actually à duplicate of #2.

**Comment by oupala** [comment]
Closing the issue, as it is a duplicate.
