### ISSUE TITLE
How to edit EasyRSS

### ISSUE THREAD

**Issue by GeoZzNL** [Alkarex/EasyRSS#30]
Hi there,

I am a fan of Android Studio. Because EasyRSS is not working in my Android Studio, i use Eclipse right now for this project only. 

Since google stopped with the Android Studio plugin for Eclipse i dont know how to transform the eclipse project to a android studio project.

Is it possible to make it Android studio compatible? Maybe its because of my Android Studio, i dont know. It just dont work.

Thank you very much!

**Comment by scastrorico** [comment]
I just imported it now from android studio (File > New > Import Project...). It was imported but then some errors appear when compiling. I suppose the problem are some libraries that have changed (method not found).

It does not seem complicated to fix, maybe it's time to think about migrating to Android Studio.

**Comment by GeoZzNL** [comment]
I cant get it work in Android Studio. I am using Eclipse now, and its working

**Comment by Alkarex** [comment]
New release https://github.com/Alkarex/EasyRSS/releases/tag/v0.7.1 with an update to the latest Android Studio 3.6.2 (IntelliJ) with Gradle, and latest Android 10.0 Q, API 29.
Help still welcome :-)
