### ISSUE TITLE
All dates being set to 1969

### ISSUE THREAD

**Issue by Asara** [Alkarex/EasyRSS#31]
Currently using 2017-xx-xx FreshRSS 1.7.0-dev on the server side, all of my items are being displayed as an epoch time of 0.  Not sure how to go about debugging this.

On the webui of FreshRSS all dates seem to be appropriately displayed, but articles downloaded to EasyRSS show them as my timezone (EDT/UTC-4) 1969.

**Comment by Alkarex** [comment]
Could you please provide a screenshot, and the address of one of the feeds you are using?

**Comment by Asara** [comment]
![1](https://user-images.githubusercontent.com/2782304/27962229-3b736bb8-62ff-11e7-9d7a-fbcdc66789ea.png)
![2](https://user-images.githubusercontent.com/2782304/27962228-3b7333b4-62ff-11e7-8b6c-d20e038eddb6.png)

The feed: http://feeds.reuters.com/reuters/topNews

**Comment by Asara** [comment]
Just for background, this is running against the dev version of FreshRSS

**Comment by Alkarex** [comment]
@Asara Hum, I cannot immediately reproduce the bug you are facing (see screenshots).
1. Could you please give a bit more information about your system (OS, PHP version, 32 or 64-bit, which database, which Android version...)?
2. Please check also whether the PHP GMP extension is well installed http://php.net/gmp
3. Did it used to work fine with some older version of FreshRSS?

![screenshot_20170707-175220](https://user-images.githubusercontent.com/1008324/27965952-cbbb931a-633d-11e7-848e-98af2241f5d2.png)
![screenshot_20170707-175246](https://user-images.githubusercontent.com/1008324/27965953-cbc7d24c-633d-11e7-9126-22242d94ac52.png)

**Comment by Asara** [comment]
OS: Debian 3.16.39-1+deb8u2 x86_64 GNU/Linux

PHP: 5.6.30-0+deb8u1

Database: PostgreSQL

Android version: Android 6.0

gmp was not installed but I installed and reloaded apache, but still nothing.

The dates show up fine on the browser side though.

**Comment by Alkarex** [comment]
Hum, there should not be any problem with this config. I am away from my development machine for some days, but my main suspicion is a bug somewhere when combining PostreSQL and EasyRSS. Let's try to find it :-)

Could you please show a few SQL lines from your *entry* table? Something like (change the name of your table):

```sql
SELECT "id", "guid", "title", "link", "date", "id_feed" FROM "freshrss_asara_entry" LIMIT 5;
```

**Comment by Asara** [comment]
`        id        |                              guid                               |                           link                           |    date    | id_feed 
------------------+-----------------------------------------------------------------+----------------------------------------------------------+------------+---------
 1496087205273555 | tag:freshrss.org,2015-03-05:freshrss-gets-a-new-website.html    | https://freshrss.org/freshrss-gets-a-new-website.html    | 1425510000 |       1
 1496087205273556 | tag:freshrss.org,2015-03-11:announce-of-the-mailing-lists.html  | https://freshrss.org/announce-of-the-mailing-lists.html  | 1426028400 |       1
 1496087205273557 | tag:freshrss.org,2015-07-30:freshrss-supports-pubsubhubbub.html | https://freshrss.org/freshrss-supports-pubsubhubbub.html | 1438207200 |       1
 1496087205273558 | tag:freshrss.org,2015-11-04:freshrss-120-is-the-new-stable.html | https://freshrss.org/freshrss-120-is-the-new-stable.html | 1446591600 |       1
 1496577852103807 | http://www.coindesk.com/?p=271472                               | http://www.coindesk.com/why-no-crypto-bubble-ico/        | 1496574000 |      15
`

**Comment by Alkarex** [comment]
Sorry for the lag. Travelling. It looks good. Are those lines among those which had a date problem? If not, you could maybe select the lines of a given feed, or the newest ones, e.g.:

```sql
SELECT "id", "guid", "link", "date", "id_feed" FROM "freshrss_asara_entry" ORDER BY "id" DESC LIMIT 10;
```

**Comment by Asara** [comment]
```
 1499777115133097 | http://www.reuters.com/article/us-palestinians-gaza-un-idUSKBN19W17T?feedType=RSS&amp;feedName=topNews                             | http://feeds.reuters.com/~r/reuters/topNews/~3/IIqnu4fa9b0/us-palestinians-gaza-un-idUSKBN19W17T                                   | 1499776140 |       6
 1499777115133096 | http://www.reuters.com/article/us-mideast-crisis-baghdadi-idUSKBN19W1AW?feedType=RSS&amp;feedName=topNews                          | http://feeds.reuters.com/~r/reuters/topNews/~3/bzsL7JGVYS0/us-mideast-crisis-baghdadi-idUSKBN19W1AW                                | 1499776080 |       6
 1499777115133095 | http://www.reuters.com/article/us-usa-trump-russia-lawyer-idUSKBN19W174?feedType=RSS&amp;feedName=topNews                          | http://feeds.reuters.com/~r/reuters/topNews/~3/6dhxOn3-0kk/us-usa-trump-russia-lawyer-idUSKBN19W174                                | 1499775180 |       6
 1499777115133094 | http://blog.namei.org/?p=690                                                                                                       | http://blog.namei.org/2017/07/11/linux-security-summit-2017-schedule-published/                                                    | 1499772600 |      27
 1499773504793894 | http://hosted.ap.org/dynamic/stories/A/AS_CHINA_JAILED_NOBEL_LAUREATE_MEDIA_BLACKOUT?SITE=AP&amp;SECTION=HOME&amp;TEMPLATE=DEFAULT | http://hosted.ap.org/dynamic/stories/A/AS_CHINA_JAILED_NOBEL_LAUREATE_MEDIA_BLACKOUT?SITE=AP&amp;SECTION=HOME&amp;TEMPLATE=DEFAULT | 1499773504 |       5
 1499773504793893 | http://www.reuters.com/article/us-toshiba-accounting-idUSKBN19W0X3?feedType=RSS&amp;feedName=topNews                               | http://feeds.reuters.com/~r/reuters/topNews/~3/kplZ_tpWQDk/us-toshiba-accounting-idUSKBN19W0X3                                     | 1499771880 |       6
 1499769903364030 | http://www.reuters.com/article/us-pepsico-results-idUSKBN19W10A?feedType=RSS&amp;feedName=topNews                                  | http://feeds.reuters.com/~r/reuters/topNews/~3/GfugkYEuLHo/us-pepsico-results-idUSKBN19W10A                                        | 1499772180 |       6
 1499769903364029 | http://www.coindesk.com/?p=276156                                                                                                  | http://www.coindesk.com/ethereums-ether-token-falls-200-hit-40-day-low/                                                            | 1499769000 |      15
 1499769903364028 | http://www.reuters.com/article/us-usa-selfdriving-idUSKBN19W0YJ?feedType=RSS&amp;feedName=topNews                                  | http://feeds.reuters.com/~r/reuters/topNews/~3/_8zcbuJSKZQ/us-usa-selfdriving-idUSKBN19W0YJ                                        | 1499768400 |       6
 1499769903364027 | http://www.coindesk.com/?p=276075                                                                                                  | http://www.coindesk.com/little-known-cryptocurrency-hedge-fund-seeks-200-million-sec-filing/                                       | 1499767200 |      15
```

It is not just one feed that is having this issue. It is all of them.

No stress about the lag, appreciate the help!

**Comment by Asara** [comment]
Dont mean to bother, any ideas what could be causing this?

**Comment by Alkarex** [comment]
I am away from my main dev machine until the end of the week, so my
debugging abilities are limited, but my current guess is a bug somewhere in
the interaction between PostgreSQL and EasyRSS, because each of them
individually work fine in another context.
If you are willing to test a little bit, I can send you a piece of code
tomorrow to log the JSON responses and hopefully isolate the problem.

Le 17 juil. 2017 20:40, "Amarpreet Minhas" <notifications@github.com> a
écrit :

**Comment by Asara** [comment]
Always willing to debug! :)

**Comment by Alkarex** [comment]
👍 Please try with this file https://github.com/Alkarex/FreshRSS/blob/debug_api/p/api/greader.php which logs a bit more info https://github.com/Alkarex/FreshRSS/commit/f57c54970d30845d0f5f988e68cd99ee26047abf#diff-d820fde0e95b775a390ca9bae6216979 in `log_api.txt`.

**Comment by Asara** [comment]
[log_api.txt](https://github.com/Alkarex/EasyRSS/files/1160132/log_api.txt)

Hope this helps. Hope I cleared up any personal info as well :x

**Comment by Alkarex** [comment]
Thanks @Asara 
Could you please try this little patch? https://github.com/FreshRSS/FreshRSS/pull/1603

**Comment by Asara** [comment]
Hey! That seems to have fixed it.  Thanks so much @Alkarex
