### ISSUE TITLE
Re-publish on F-Droid

### ISSUE THREAD

**Issue by Alkarex** [Alkarex/EasyRSS#32]
* https://github.com/Alkarex/EasyRSS/issues/4#issuecomment-309673011
* https://github.com/Alkarex/EasyRSS/issues/27#issuecomment-309672688
* https://f-droid.org/repository/browse/?fdid=org.freshrss.easyrss
* https://f-droid.org/wiki/page/org.freshrss.easyrss
* https://gitlab.com/fdroid/fdroiddata/issues/788#note_35541404
* https://forum.f-droid.org/t/many-old-unmaintained-apps-have-been-archived/670

**Comment by Alkarex** [comment]
My plan is:
1. Bump the version number to get it back in F-Droid as-is. Done https://github.com/Alkarex/EasyRSS/releases/tag/v0.6.08
2. Update development code to the latest Android Studio. Check that is still works for F-Droid.
3. Make functional changes / updates / fixes (contributions much welcome)

**Comment by mimi89999** [comment]
@Alkarex 
```
michel@debian:~/git/fdroiddata$ fdroid build -vl org.freshrss.easyrss
INFO: Building version 0.6.08 (608) of org.freshrss.easyrss
INFO: Getting source for revision v0.6.08
INFO: Creating local.properties file at build/org.freshrss.easyrss/local.properties
INFO: Running 'prebuild' commands in build/org.freshrss.easyrss
+ echo -e 'java.source=1.7\njava.target=1.7'
+ mv libs/jackson-core/src/main/java/com src/
+ mv libs/HtmlCleaner/src/org src/org2
+ rm -fR libs/
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Invalid or unsupported command "update lib-project -p ."

Supported commands are:
android list target
android list avd
android list device
android create avd
android move avd
android delete avd
android list sdk
android update sdk
ERROR: Could not build app org.freshrss.easyrss: Failed to update project at .
==== detail begin ====
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Invalid or unsupported command "update lib-project -p ."

Supported commands are:
android list target
android list avd
android list device
android create avd
android move avd
android delete avd
android list sdk
android update sdk
==== detail end ====
INFO: Finished.
INFO: 1 builds failed
```
Google depreciated ant builds.

**Comment by Alkarex** [comment]
@mimi89999 Thanks. I am not sure where this `update lib-project` command comes from (not from my source code), but I guess this is the file that needs to be updated: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.freshrss.easyrss.txt

**Comment by Alkarex** [comment]
For reference https://f-droid.org/docs/Build_Metadata_Reference/ (it looks like F-Droid still uses Ant by default)

**Comment by Alkarex** [comment]
@mimi89999 Would you be able to try to tune https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.freshrss.easyrss.txt to make it compile? The project uses no special feature and has no external library, so it should be compilable with any toolchain. https://gitlab.com/fdroid/fdroiddata/tree/master/templates

**Comment by Frenzie** [comment]
Looks like it worked out. An update showed up in my F-Droid app. It fixed it up so that images are actually displayed to boot. ;-)

**Comment by Frenzie** [comment]
@Alkarex @mimi89999 Looks like the 0.7.2 tag hasn't built yet, is that expected?

**Comment by Alkarex** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6628
