### ISSUE TITLE
Dates on server and app not the same

### ISSUE THREAD

**Issue by planetahuevo** [Alkarex/EasyRSS#33]
Hi, 
I did a new fresh install of the app and of the server with the 1.7.0 release. 
Added 3 feeds. One of them is actual. 
For that one, dates on the web are fine but on the app, all appear with the same date, 2017-08-09 22:50
Which is the date of the latest post from that feed. 
And now I see that this happens with all 3 feeds. The dates on the app for all posts on each feed is the date of the latest post of each feed.

**Comment by Alkarex** [comment]
Hello @planetahuevo ,
Do you still have the problem after the feeds have been refreshed a few times?
If yes, could you please try again with this patch? https://github.com/FreshRSS/FreshRSS/pull/1603
And if does not help, could you please provide the same information as used for the debugging of https://github.com/Alkarex/EasyRSS/issues/31

**Comment by Frenzie** [comment]
Likely the same issue as https://github.com/FreshRSS/FreshRSS/issues/2759

See https://github.com/javerous/freshrss-greader-redate for a current workaround.

**Comment by Alkarex** [comment]
Should be fixed by https://github.com/Alkarex/EasyRSS/pull/49
Tests welcome

**Comment by Alkarex** [comment]
https://github.com/Alkarex/EasyRSS/releases/tag/v0.7.2
