### ISSUE TITLE
Article url with XML escaped query parameters fails to load

### ISSUE THREAD

**Issue by mappu** [Alkarex/EasyRSS#35]
Hi,

For this RSS feed: https://www.phoronix.com/rss.php inside FreshRSS

You can see that the `link` attributes use HTML/XML escaping, which transforms `&` parameters in the URL into `&amp;`. e.g. `<link>http://www.phoronix.com/scan.php?page=news_item&amp;px=Qualcomm-Centriq-2400</link>`

In EasyRSS, viewing the link for this page opens the literal URL http://www.phoronix.com/scan.php?page=news_item&amp;px=Qualcomm-Centriq-2400 ... which is invalid and so the website redirects to the homepage.

EasyRSS must perform HTML/XML entity decoding more correctly.

Using EasyRSS 0.6.08 from F-Droid.

**Comment by Alkarex** [comment]
Should be fixed on FreshRSS side in https://github.com/FreshRSS/FreshRSS/pull/1686
