### ISSUE TITLE
No page title in EasyRSS since FreshRSS 1.10

### ISSUE THREAD

**Issue by monsieurpouet** [Alkarex/EasyRSS#36]
Hi !

I use FreshRSS 1.10 on Debian 9.3 with apache 2.4.25.
Since the freshrss update to the 1.10, EasyRSS don't show the website title anymore.
I've my title of article, but I don't know this comes from.
Instead of the website title, I've a "-"
I have not this problem in the freshrss web app.

**Comment by Alkarex** [comment]
Sorry for the bug. This has just been fixed in the /dev version of FreshRSS https://github.com/FreshRSS/FreshRSS/pull/1800 and a new version 1.10.1 of Fresh RSS will be released very soon.

**Comment by monsieurpouet** [comment]
No problem Alkarex =)
I didn't know the problem come from freshrss. I thought that came Easy RSS
