### ISSUE TITLE
Publish on F-droid

### ISSUE THREAD

**Issue by Alkarex** [Alkarex/EasyRSS#4]
Publish the application on https://f-droid.org.
More info: https://github.com/FreshRSS/FreshRSS/issues/328#issuecomment-36460230

**Comment by Alkarex** [comment]
I still need to take care of that. I am not sure whether it would be better to change the name of the app' or not. If yes, I suggest "InnocentRSS".

**Comment by wilfried18** [comment]
Oui pourquoi pas , sinon cela ne pourrait pas étre la version officiel pour android de freshrss ?

**Comment by Alkarex** [comment]
I have started to work on publishing to F-Droid. Here is my draft of metadata https://gitlab.com/Alkarex/fdroiddata/blob/EasyRSS/metadata/com.pursuer.reader.easyrss.txt
Any help/feedback welcome.

**Comment by wilfried18** [comment]
@Alkarex Tu devais changer de nom pour l'appli ?

**Comment by Alkarex** [comment]
@wilfried18 It looks like EasyRSS is [not available any more on Google Play Store](https://market.android.com/details?id=com.pursuer.reader.easyrss), so at least this part of the naming problem is gone. But changing name is still an option if needed. I also need to find what ID to use instead of `com.pursuer.reader.easyrss`. Maybe `easyrss.freshrss.org` or similar.

**Comment by wilfried18** [comment]
@Alkarex Je pense (pour ma part) que changer le nom te sera favorable , histoire de rendre a césar ce qui est a césar , logiquement un fork d'une apps, logiciel ne garde pas le méme nom (histoire de pas se tromper de quel version on parle) , aprés c'est mon avis perso , c'est a toi de décider

**Comment by Alkarex** [comment]
Pull request to F-Droid https://gitlab.com/fdroid/fdroiddata/merge_requests/786

**Comment by Alkarex** [comment]
The pull request has just been merged https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.freshrss.easyrss.txt

```
Categories:Internet,Reading
License:GPLv3
Web Site:https://github.com/Alkarex/EasyRSS/blob/HEAD/README.md
Source Code:https://github.com/Alkarex/EasyRSS
Issue Tracker:https://github.com/Alkarex/EasyRSS/issues

Auto Name:EasyRSS
Summary:RSS reader compatible with Google Reader API
Description:
An Android client for RSS services compatible with Google Reader API,
such as the open source self-hosted project [http://freshrss.org/ FreshRSS].

[https://raw.githubusercontent.com/Alkarex/EasyRSS/master/CHANGELOG.md Changelog]
.

Repo Type:git
Repo:https://github.com/Alkarex/EasyRSS

Build:0.6.06,606
    disable=dependencies
    commit=v0.6.06
    prebuild=echo -e 'java.source=1.7\njava.target=1.7' > ant.properties && \
        sed -i -e '/<properties>/a<maven.compiler.source>1.7</maven.compiler.source>\n<maven.compiler.target>1.7</maven.compiler.target>\n' libs/jackson-core/pom.xml 
    build=pushd libs/jackson-core && $$MVN3$$ package && popd

Auto Update Mode:Version v%v
Update Check Mode:Tags
Current Version:0.6.06
Current Version Code:606
```

**Comment by Alkarex** [comment]
Merged, and enabled in F-Droid:
```
Categories:Internet,Reading
License:GPLv3
Web Site:https://github.com/Alkarex/EasyRSS/blob/HEAD/README.md
Source Code:https://github.com/Alkarex/EasyRSS
Issue Tracker:https://github.com/Alkarex/EasyRSS/issues

Auto Name:EasyRSS
Summary:RSS reader compatible with Google Reader API
Description:
An Android client for RSS services compatible with Google Reader API,
such as the open source self-hosted project [http://freshrss.org/ FreshRSS].

[https://raw.githubusercontent.com/Alkarex/EasyRSS/master/CHANGELOG.md Changelog]
.

Repo Type:git
Repo:https://github.com/Alkarex/EasyRSS

Build:0.6.06,606
    commit=v0.6.06
    prebuild=echo -e 'java.source=1.7\njava.target=1.7' > ant.properties && \
        mv libs/jackson-core/src/main/java/com src/ && \
        mv libs/HtmlCleaner/src/org src/org2 && \
        rm -fR libs/

Auto Update Mode:Version v%v
Update Check Mode:Tags
Current Version:0.6.06
Current Version Code:606
```

**Comment by Alkarex** [comment]
Build successful :-) https://f-droid.org/wiki/page/org.freshrss.easyrss/lastbuild

**Comment by Alkarex** [comment]
EasyRSS is now available in F-Droid :-)
https://f-droid.org/repository/browse/?fdfilter=easyrss&fdid=org.freshrss.easyrss

**Comment by Alkarex** [comment]
[![f-droid-button_bigger](https://cloud.githubusercontent.com/assets/1008324/7830569/e744b9ae-044e-11e5-9009-ab3285d216ab.png)](https://f-droid.org/repository/browse/?fdid=org.freshrss.easyrss)

**Comment by Alkarex** [comment]
It seems to have disappeared from F-Droid https://f-droid.org/repository/browse/?fdid=org.freshrss.easyrss
I am not sure why.

**Comment by wilfried18** [comment]
@Alkarex Sa doit étre une erreur , ta essayer de contacter un administrateur ou en parler dans le forum ? c'est bizarre en effet

**Comment by Alkarex** [comment]
Related comment: https://github.com/Alkarex/EasyRSS/issues/27#issuecomment-315854364

**Comment by Alkarex** [comment]
@wilfried18 Ticket dédié pour la re-soumission à F-Droid https://github.com/Alkarex/EasyRSS/issues/32
