### ISSUE TITLE
https support on another port than 443

### ISSUE THREAD

**Issue by vmisson** [Alkarex/EasyRSS#40]
Hello,

I'm running an instance of FreshRSS in https on port 8080.
I'm not able to connect EasyRSS to it and after some network traces it seems EasyRSS is trying to connect in http on port 8080 and not https.

Can you please add the support of https on another port than 443 ?
Thanks in advance.

**Comment by PLanB2008** [comment]
This already seems to work. Just pass the port after the url but before the freshrss path.

eg: https://myrss.domain.com:8080/freshrss/p/api/geader.php
