### ISSUE TITLE
how to compile on Android Studio 3.5.2?

### ISSUE THREAD

**Issue by aguaviva** [Alkarex/EasyRSS#43]
I'd like to add web authentication, I tried using Android Studio 3.5.2 but the import feature didn't work. 

Thanks!

**Comment by Frenzie** [comment]
Implemented in #48.

**Comment by Alkarex** [comment]
Yes, the project is migrated at last to the Latest Android Studio with Gradle and compatibility with Android 10.0 Q, API 29

**Comment by aguaviva** [comment]
You guys are awesome, thank you very much!
