### ISSUE TITLE
fdroid -> 0.6.08 from 2017 is that correct?

### ISSUE THREAD

**Issue by Mannshoch** [Alkarex/EasyRSS#44]
is that correct, that Easyrss ersion 0.6.08 frpm 2017 is the actual version?

**Comment by Alkarex** [comment]
Hello,
Yes, there has not been any new update lately. Help most welcome :-)

**Comment by Alkarex** [comment]
New release https://github.com/Alkarex/EasyRSS/releases/tag/v0.7.1 with an update to the latest Android Studio 3.6.2 (IntelliJ) with Gradle, and latest Android 10.0 Q, API 29.
Help still welcome :-)

**Comment by Alkarex** [comment]
P.S.: F-Droid coming soon
