### ISSUE TITLE
No sync of star updates

### ISSUE THREAD

**Issue by koelscha** [Alkarex/EasyRSS#46]
EasyRSS does not sync stars. Steps to reproduce:
1) Mark an article as starred
2) Sync EasyRSS
3) Unstar article using the Webinterface
4) Sync EasyRSS

Result: Article is still starred in EasyRSS.

Using EasyRSS 0.6.08 and FreshRSS 1.15.2

**Comment by koelscha** [comment]
Oh, just saw it's a duplicate of a 2014 bug #2 so I guess chances of a fix are pretty slim

**Comment by Alkarex** [comment]
Help welcome ;-)
(My free software time is mostly for FreshRSS)
