### ISSUE TITLE
[0.7.4] Which URL and login/pass to use ?

### ISSUE THREAD

**Issue by Draky50110** [Alkarex/EasyRSS#53]
Hello.

Got a FreshRSS on https://subdomain.domain.com/frss/ which is displayed on /p/i at the end of URL, with a login/pass

When trying to identify with EasyRSS 0.7.4 : can't login.

Which URL do I need to enter (should be displayed on login screen or autodetected ?) ?

Just read on old issue that there is an API password ?
Which settings do I need to check on my FreshRSS ?

**Comment by Alkarex** [comment]
Hello,
First, it is best to avoid exposing the `/p/` in your URL. You server should ideally be set up to point into the `./FreshRSS/p/` folder of your FreshRSS installation.
See the doc https://freshrss.github.io/FreshRSS/en/admins/10_ServerConfig.html

If you manually change your installation path after URL is installed, remember to update `base_url` in `./FreshSS/data/config.php`

Alternatively, try [our Docker image](https://hub.docker.com/r/freshrss/freshrss/) where this configuration is done properly.

In any case, browse to the `.../api/` URL of your FreshRSS, and it will display your API endpoints. In EasyRSS, you need to type the full address that ends with `/api/greader.php`

**Comment by Alkarex** [comment]
Remember also to activate the API in FreshRSS, and to set an API password for your user in FreshRSS

**Comment by Draky50110** [comment]
Thanks, working.
