### ISSUE TITLE
Allow clear text HTTP traffic

### ISSUE THREAD

**Issue by DanSman** [Alkarex/EasyRSS#54]
Hi

First of all, I'm so happy that you updated this beautiful reader!
I'm using it for a few years now for a freshrss server at home and I love it ;)
There is no proper security involved because I use it only at home. Any chance to disable it?
Otherwise, I could try self signed certificates but I guess android doesn't like it?!

What do you think? 

Thanks again! 
Dan

**Comment by Alkarex** [comment]
Hello,
I suggest you use HTTPS also at home.
It is very easy to do with for instance Traefik, with automatic gratis HTTPS certificates
https://github.com/FreshRSS/FreshRSS/issues/2918#issuecomment-616668682
https://github.com/FreshRSS/FreshRSS/tree/master/Docker

I have not tried recently in plain HTTP, can you please explain again what is not working?

Is it maybe related to https://github.com/Alkarex/EasyRSS/issues/55

**Comment by AeliusSaionji** [comment]
The latest update of this app refuses to connect over http. It throws an error saying http is not allowed. This is not true of the previous release.

I second this feature request. I access my LAN via a self hosted VPN and it seems rather silly that I am _required_ to acquire externally validated https certs for my closed off internal network.

I actually did go ahead and set up https anyway, but the app now reports http `400` errors.

**Comment by DanSman** [comment]
I have the same set up like Aelius.  
  
I have created self-signed certificates. As I mentioned before, I'm having some difficulties getting the app to work now. I have added the certificate to the Android system, but I still can't log on to the server now.   
  
I am trying to log in at https://$host:$port/api/greader.php. The result of the link is 'OK'. The API password is set up.  
  
There are no server logs because I can't get that far, I guess.

Android has some logs:  
```
05-04 17:48:16.517 W/System.err(2575): org.freshrss.easyrss.network.AbsDataSyncer$DataSyncerException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

**Comment by Alkarex** [comment]
I will check to allow HTTP

**Comment by DanSman** [comment]
Maybe you can implement that some how? 
https://gitlab.com/bitfireAT/cert4android

Sry, I don't know how hard it is :/

**Comment by Alkarex** [comment]
The current /master branch seems to connect fine to a FreshRSS server over HTTP. I will issue a new build

**Comment by Alkarex** [comment]
https://github.com/Alkarex/EasyRSS/releases/tag/v0.7.6
