### ISSUE TITLE
0.7.4 Crash when reading non https article 

### ISSUE THREAD

**Issue by nesies** [Alkarex/EasyRSS#55]
I upgraded from 0.6.08 to 0.7.4 (F-droid). 

Since then, i can read http articles. 

Examples :
https://rss.framasoft.org/
http://rss.slashdot.org/Slashdot/slashdot

When reading an article from http rss slashdot
- click "original page"-> the application crash. 
- click "mobilizer"-> displays "content van not be displayed" 
- then click "orignal page"-> "net::ERR_CLEARTEXT_NOT_PERMITTED"
(screenshot attached) 

If i read article from a https, everything is ok

![_20200425_130505](https://user-images.githubusercontent.com/107966/80278372-f98b8000-86f5-11ea-97bc-9cd45d02aa38.JPG)

**Comment by Alkarex** [comment]
Thanks for the bug report.
For documentation: https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

**Comment by Alkarex** [comment]
Fix in https://github.com/Alkarex/EasyRSS/pull/56

**Comment by Alkarex** [comment]
I am using http://rss.slashdot.org/Slashdot/slashdotMain which gives HTTPS links

**Comment by nesies** [comment]
Works when click mobilizer then Original 
but the app still crash when i only click "original page"

**Comment by Alkarex** [comment]
@nesies Ah, the other bug seems to be a regression from https://github.com/Alkarex/EasyRSS/pull/52/files

**Comment by Alkarex** [comment]
The second bug should be fixed with https://github.com/Alkarex/EasyRSS/pull/57

**Comment by Alkarex** [comment]
https://github.com/Alkarex/EasyRSS/releases/tag/v0.7.6
