### ISSUE TITLE
All articles marked as unread on first run

### ISSUE THREAD

**Issue by nesies** [Alkarex/EasyRSS#58]
To testaa bugfix, i uninstalled and did a fresh install, specified url, login, password.
It synched.
But all articles are marked as unread.
If i set on as read, It works and persistent after an application restart. 

Server FreshRss 1.15. 4

**Comment by Alkarex** [comment]
I have tried a bit and cannot reproduce. Let me make a new release, and see whether you still face the problem

**Comment by nesies** [comment]
Here some screenshot with 0.7.4

![_20200508_221625](https://user-images.githubusercontent.com/107966/81445746-c75c3280-9179-11ea-8a7f-e5c19d117b8b.JPG)
![_20200508_221557](https://user-images.githubusercontent.com/107966/81445750-cb885000-9179-11ea-9006-27986a13fa38.JPG)

**Comment by Alkarex** [comment]
If you can, please try with the latest [/master branch of FreshRSS](https://github.com/FreshRSS/FreshRSS) (1.16.1-dev) (also available via Docker) and the latest EasyRSS https://github.com/Alkarex/EasyRSS/releases/tag/v0.7.6
