### ISSUE TITLE
Invalid status 400 from freshrss

### ISSUE THREAD

**Issue by AeliusSaionji** [Alkarex/EasyRSS#59]
Hello!
The very first time I run the app, I can log in and sync everything. But EasyRSS cannot sync again, I just get this error.

![image](https://user-images.githubusercontent.com/4342746/80322116-bbbf5200-87f0-11ea-9da6-67438b07ff67.png)

**Comment by Alkarex** [comment]
Sorry for the delay. Try with the /master version of FreshRSS and/or with EasyRSS 0.7.6

**Comment by AeliusSaionji** [comment]
It turns out it was a configuration error on my end. I was using lighttpd, I switched to nginx, and the issue is resolved. I bet it was something to do with the `PATH_INFO` variable for php-fpm.

Thanks, sorry for the trouble.
