### ISSUE TITLE
i want translate it Chinese

### ISSUE THREAD

**Issue by makeye** [Alkarex/EasyRSS#65]
i want to translate this

**Comment by Alkarex** [comment]
Hello @makeye 
There is already a Chinese translation, see https://github.com/Alkarex/EasyRSS/tree/master/app/src/main/res/values-zh-rCN , but improvements are welcome

**Comment by makeye** [comment]
👌🏻， can you make Tutorials for this APP。i dont know how to use😂

**Comment by Alkarex** [comment]
EasyRSS is an app that requires a server such as FreshRSS https://github.com/FreshRSS/FreshRSS
So start by trying out FreshRSS (which has a Web interface)
