### ISSUE TITLE
Audio attachments can be played but can't be downloaded

### ISSUE THREAD

**Issue by jfcolom** [Alkarex/EasyRSS#78]
If the RSS item has some audio file attached, the app shows a "mini player" to play the audio. Apparently the "mini player" allows you to download the media, but the menu option is always disabled (the media can be downloaded when the item is accessed directly with FreshRSS).

Maybe it is an issue with Android > 12

Good app! Thanks a lot!

**Comment by Alkarex** [comment]
Hello,
I do not plan to add more features to this app, only basic maintenance. But PR welcome if anyone comes with a fix.
You could try the Web version of FreshRSS or one of the other apps:
https://github.com/FreshRSS/FreshRSS/blob/edge/README.md#apis--native-apps
(unfortunately, there is not yet one app which passes all my minimum criteria, and which I could recommend, but a few are under active development)

**Comment by jfcolom** [comment]
Thank you for your answer. EasyRSS is the the most fitting app for me, as it allows me to review my RSS content while I'm offline.

Regarding to the disabled Download option in the audio player, I'm now inclined to think that it is an issue on the FreshRSS side. When I browse FreshRSS using the smartphone's browser, I get a "Network error" when trying to download the media using the player (it works properly when browsing FreshRSS from a desktop computer). EasyRSS appears not to show the error message, so the Download option seems "disabled" to me, but it is throwing an error instead.

**Comment by jfcolom** [comment]
Trying to narrow down my issue, I've come to know that the problem is related to the way the <audio> HTML5 tag is dealt with in different browsers. For some reason, the "Download" option raises error o does nothing from my smartphone (in EasyRSS or FreshRSS web). However, it works ok from my desktop.

Now I can figure it out why is there an additional download link on the FreshRSS web page (the floppy disk symbol). Unfortunately, this link does not appear in EasyRSS 

[related](https://github.com/FreshRSS/FreshRSS/issues/1236)

**Comment by Alkarex** [comment]
Could you provide an example of feed and a screenshot or two?

**Comment by jfcolom** [comment]
Sure!

This screenshot is from EasyRSS, showing an item that includes a media resource (I think it is called "enclosure" in the RSS jargon). The app shows a basic player with an option to Download the stream as a media file as well as another one to set the playback speed. In my smartphone, the "Download" option is irresponsive.

![screenshot_easyrss](https://github.com/Alkarex/EasyRSS/assets/31566526/8c3971d2-eadc-4b6e-bba7-11a39527d35e)

A similar behaviour is shown by FreshRSS with the very same item from my smartphone. In this case, though, an error message is notified by my browser ("Network error"). However, FreshRSS, provides an extra "floppy disk" button that allows to download the file (see next screenshot)

![screenshot_freshrss](https://github.com/Alkarex/EasyRSS/assets/31566526/6447d6c7-4e93-4ebb-993f-dc140daec0b9)

I think this happens with any feed providing "enclosures". For example:

[https://feeds.acast.com/public/shows/62b0ada25c7ea10012f541cb](https://feeds.acast.com/public/shows/62b0ada25c7ea10012f541cb)

**Comment by Alkarex** [comment]
In FreshRSS Web interface, can you try a long click on the media? It should offer an option to download (tested on Firefox for mobile)

**Comment by jfcolom** [comment]
In FressRSS web interface, I don't get any additional option when doing "long click" on the player. I'm using Brave for mobile. When tapping on the menu (three vertical points on the right of player, see second screenshot) I get the very same options as in EasyRSS: Download and Playback speed. Download triggers a "Network error"; the floppy disk button works ok. From a desktop computer, the two links work ok.

Having a look at the HTML source code, it seems to me that it has to do with the way that the browser deals with the HTML "audio" tag.
