### ISSUE TITLE
Quickly mark many postings as read 

### ISSUE THREAD

**Issue by MarcusWolschon** [Alkarex/EasyRSS#79]
Skimming the headline of a lot of daily news,
it takes a long time to long-press each one to mark it as read without opening all the time uninteresting stuff.
Swiping to reveal a button or a way to to mark many posting and mark them all as read would be greatly appreciated.

**Comment by Alkarex** [comment]
Have you considered the automatic mark as read on scroll? Then you can do the opposite of what you do now, namely giving a star (or force mark as unread) the articles, which you want to keep for later

**Comment by Alkarex** [comment]
I am archiving this project, as there are better open source alternatives, more actively maintained and developed:
check [Readrops](https://github.com/readrops/Readrops) or [Capy Reader](https://github.com/jocmp/capyreader)
