### ISSUE TITLE
Can't install the .apk file on my Android 4.3.

### ISSUE THREAD

**Issue by siick** [Alkarex/EasyRSS#9]
Hello.
I've check in my phone options the right to install "untrusted" software, then i've downloaded the .apk and i've resend it by mail to open it on my phone. When i try to open it i've got that message : 
Erreur d'analyse : 
Un problème est survenu lors de l'analyse du package.
May have an idea of what is the problem?

**Comment by Alkarex** [comment]
It's been a while, but let me know if there is anything new. New version 0.6.04 available with support for TLS 1.2.
